services:
  traefik:
    image: traefik:3.0
    ports:
      - 80:80
      - 443:443
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.services.traefik-dashboard.loadbalancer.server.port=8090
      - traefik.http.routers.traefik-dashboard-http.entrypoints=http
      - traefik.http.routers.traefik-dashboard-http.rule=Host(`proxy.fastapi.jumpingcrab.com`)
      - traefik.http.routers.traefik-dashboard-https.entrypoints=https
      - traefik.http.routers.traefik-dashboard-https.rule=Host(`proxy.fastapi.jumpingcrab.com`)
      - traefik.http.routers.traefik-dashboard-https.tls=true
      - traefik.http.routers.traefik-dashboard-https.tls.certresolver=le
      - traefik.http.routers.traefik-dashboard-https.service=api@internal
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.traefik-dashboard-http.middlewares=https-redirect
      - traefik.http.middlewares.admin-auth.basicauth.users=admin:$apr1$LI7xdv7t$U1wKnaVuvbFdkPtYqCRnQ1
      - traefik.http.routers.traefik-dashboard-https.middlewares=admin-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
#      - --certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.le.acme.email=jhudeyhemi51@gmail.com
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --log
      - --api
    networks:
      - traefik-public

  db:
    image: postgres:12
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=changethis123
      - POSTGRES_USER=app
      - POSTGRES_DB=app

  adminer:
    image: adminer
    restart: always
    networks:
      - traefik-public
      - default
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.adminer-http.rule=Host(`db.fastapi.jumpingcrab.com`)
      - traefik.http.routers.adminer-http.entrypoints=http
      - traefik.http.routers.adminer-http.middlewares=https-redirect
      - traefik.http.routers.adminer-https.rule=Host(`db.fastapi.jumpingcrab.com`)
      - traefik.http.routers.adminer-https.entrypoints=https
      - traefik.http.routers.adminer-https.tls=true
      - traefik.http.routers.adminer-https.tls.certresolver=le
      - traefik.http.services.adminer.loadbalancer.server.port=8080

  backend:
    build:
      context: ./backend
    restart: always
    networks:
      - traefik-public
      - default
    depends_on:
      - db
    environment:
      - DOMAIN=fastapi.jumpingcrab.com
      - ENVIRONMENT=production
      - BACKEND_CORS_ORIGINS="http://fastapi.jumpingcrab.com,http://fastapi.jumpingcrab.com:5173,https://fastapi.jumpingcrab.com,https://fastapi.jumpingcrab.com:5173"
      - SECRET_KEY=changethis123
      - FIRST_SUPERUSER=devops@hng.tech
      - FIRST_SUPERUSER_PASSWORD=devops#HNG11
      - USERS_OPEN_REGISTRATION=True
      - EMAILS_FROM_EMAIL=jhudeyhemi51@gmail.com
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=changethis123
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.services.backend.loadbalancer.server.port=80
      - traefik.http.routers.backend-http.rule=(Host(`fastapi.jumpingcrab.com`) || Host(`www.fastapi.jumpingcrab.com`)) && (PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`))
      - traefik.http.routers.backend-http.entrypoints=http
      - traefik.http.routers.backend-https.rule=(Host(`fastapi.jumpingcrab.com`) || Host(`www.fastapi.jumpingcrab.com`)) && (PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`))
      - traefik.http.routers.backend-https.entrypoints=https
      - traefik.http.routers.backend-https.tls=true
      - traefik.http.routers.backend-https.tls.certresolver=le
      - traefik.http.middlewares.www-redirect.redirectregex.regex=^http(s)?://www.(fastapi.jumpingcrab.com)/(.*)
      - traefik.http.middlewares.www-redirect.redirectregex.replacement=http$${1}://fastapi.jumpingcrab.com/$${3}
      - traefik.http.routers.backend-http.middlewares=https-redirect
      - traefik.http.routers.backend-https.middlewares=www-redirect
      - traefik.http.middlewares.www-redirect.redirectregex.permanent=true

  frontend:
    restart: always
    networks:
      - traefik-public
      - default
    build:
      context: ./frontend
      args:
        - VITE_API_URL=https://fastapi.jumpingcrab.com
        - NODE_ENV=production
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.services.frontend.loadbalancer.server.port=80
      - traefik.http.routers.frontend-http.rule=Host(`fastapi.jumpingcrab.com`) || Host(`www.fastapi.jumpingcrab.com`)
      - traefik.http.routers.frontend-http.entrypoints=http
      - traefik.http.routers.frontend-https.rule=Host(`fastapi.jumpingcrab.com`) || Host(`www.fastapi.jumpingcrab.com`)
      - traefik.http.routers.frontend-https.entrypoints=https
      - traefik.http.routers.frontend-https.tls=true
      - traefik.http.routers.frontend-https.tls.certresolver=le
      - traefik.http.middlewares.www-redirect.redirectregex.regex=^http(s)?://www.(fastapi.jumpingcrab.com)/(.*)
      - traefik.http.middlewares.www-redirect.redirectregex.replacement=http$${1}://fastapi.jumpingcrab.com/$${3}
      - traefik.http.routers.frontend-https.middlewares=www-redirect
      - traefik.http.routers.frontend-http.middlewares=https-redirect
      - traefik.http.middlewares.www-redirect.redirectregex.permanent=true

volumes:
  app-db-data:
  traefik-public-certificates:

networks:
  traefik-public:
